# -*- coding: utf-8 -*-
"""NLP_MODEL_EXCELR(Final)TODAY(F).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k609nnd3PKaC9GicdTePbazHcn4tQb0d
"""

# Commented out IPython magic to ensure Python compatibility.
import nltk # Natural Language Toolkit
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')
import pandas as pd
from text_cleaner import TextCleaner
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import seaborn as sns
import matplotlib.pyplot as plt
import re # Regular Expression
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline
!pip install WordCloud
from wordcloud import WordCloud,STOPWORDS
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LogisticRegression
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

df = pd.read_excel("drugsCom_raw.xlsx")

df.head(10)

df = df.drop(['Unnamed: 0','rating','date','usefulCount'],axis = 1)

df.head(10)

filtered_df = df[df['condition'].isin(['Depression','High Blood Pressure','Diabetes, Type 2'])]
filtered_df = filtered_df.reset_index(drop=True)
print(filtered_df.index)

filtered_df.head(10)

filtered_df.isnull().sum()

filtered_df.duplicated().sum()

filtered_df[filtered_df.duplicated()]

filtered_df = filtered_df.drop_duplicates()

filtered_df.duplicated().sum()

filtered_df.info()



range(len(filtered_df))

pd.set_option('display.max_colwidth', None)

filtered_df.head(10)

#review_text = " ".join(filtered_df['clean_review'].astype(str))
#drug_text = " ".join(filtered_df['drugName'].astype(str))

#wc = WordCloud(background_color='grey').generate(review_text)
#plt.imshow(wc)#image show
#plt.axis('off')
#plt.title("DrugName",size=25)

#wc = WordCloud(background_color='grey').generate(drug_text)
#plt.imshow(wc)#image show
#plt.axis('off')
#plt.title("DrugName",size=25)

X = filtered_df[['review', 'drugName']]
y = filtered_df['condition']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

def scale_down_features(x):
    return x * 0.1

# 1. Create a custom function to multiply feature arrays by 0.1 (down-weighting)
downweight_transformer = FunctionTransformer(lambda x: x * 0.1, accept_sparse=True)

# 2. Pipeline for the 'review' column
review_sub_pipeline = ImbPipeline([
    ('cleaner', TextCleaner()), # Uses your imported cleaner untouched
    ('tfidf', TfidfVectorizer(max_features=20000, ngram_range=(1,2)))
])

# 3. Pipeline for the 'drugName' column
drug_sub_pipeline = ImbPipeline([
    ('cleaner', TextCleaner()), # Uses your imported cleaner untouched
    ('tfidf', TfidfVectorizer(max_features=1000)),
    ('downweight', downweight_transformer) # Shrinks its mathematical importance
])

# 4. Use ColumnTransformer to process columns separately by name
preprocessor = ColumnTransformer([
    ('review_features', review_sub_pipeline, 'review'),
    ('drug_features', drug_sub_pipeline, 'drugName')
])

# 5. Build the Master Pipeline
pipeline = ImbPipeline([
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)), # Handles class imbalance safely after vectorization
    ('model', LogisticRegression(max_iter=1000))
])

# 6. Fit the pipeline on your new training sets
pipeline.fit(X_train, y_train)

import joblib
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from imblearn.pipeline import Pipeline as ImbPipeline
from imblearn.over_sampling import SMOTE

# --- FIX: Define a standard, named function instead of a lambda ---
def scale_down_features(x):
    return x * 0.1

# Pass the named function to the transformer
downweight_transformer = FunctionTransformer(scale_down_features, accept_sparse=True)


# 2. Pipeline for the 'review' column
review_sub_pipeline = ImbPipeline([
    ('cleaner', TextCleaner()),
    ('tfidf', TfidfVectorizer(max_features=20000, ngram_range=(1,2)))
])

# 3. Pipeline for the 'drugName' column
drug_sub_pipeline = ImbPipeline([
    ('cleaner', TextCleaner()),
    ('tfidf', TfidfVectorizer(max_features=1000)),
    ('downweight', downweight_transformer)
])

# 4. Use ColumnTransformer to process columns separately by name
preprocessor = ColumnTransformer([
    ('review_features', review_sub_pipeline, 'review'),
    ('drug_features', drug_sub_pipeline, 'drugName')
])

# 5. Build the Master Pipeline
pipeline = ImbPipeline([
    ('preprocessor', preprocessor),
    ('smote', SMOTE(random_state=42)),
    ('model', LogisticRegression(max_iter=1000))
])

# 6. Fit the pipeline on your training sets
pipeline.fit(X_train, y_train)


# --- SAVE CODES ---
job_list = sorted(filtered_df['drugName'].unique())

# These will now save successfully without crashing!
joblib.dump(pipeline, "drug_condition_model(gem).pkl")
joblib.dump(job_list, "drug_list(gem).pkl")

pred = pipeline.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

